version: '2'
services:
  app:
    build: .
    build:
      context: .
      dockerfile: Dockerfile.poolsclosed
    image: chrisevett/poolsclosed
    links:
      # this is in the form service:alias 
      - redis:compose_redis
    ports: 
      - "42069:42069"
  redis:
    build: .
    build: 
      context: .
      dockerfile: Dockerfile.redis
    image: chrisevett/redis
    volumes: 
     - redisvolume:/data
volumes:
  redisvolume:
    driver: local
